### ISSUE TITLE
Chore: add code of conduct

### ISSUE THREAD

**Issue by nokome** [stencila/dockter#22]
Our standard CoC from https://github.com/stencila/policies/blob/master/CONDUCT.md should be added to this repo and linked to from README in the Develop section.

**Comment by apawlik** [comment]
Would it make more sense to add a `CONTRIBUTE.md` and there put a section on adhering to the CoC? Like we did in other repos. I *think* but may be wrong, that we agreed to remove CoC from repos and keep it in our `policies` repository, referring to it where needed?

**Comment by nokome** [comment]
Yes, that makes sense. I'd prefer to keep the "dev quick start" in the README but we could have more details e.g. commit format in `CONTRIBUTING.md`. Good examples include:

- https://github.com/atom/atom/blob/master/CONTRIBUTING.md
- https://github.com/scikit-learn/scikit-learn/blob/master/CONTRIBUTING.md
