### ISSUE TITLE
RParser: TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by apawlik** [stencila/dockter#24]
When trying to compile folder with only one `R` file  https://raw.githubusercontent.com/swcarpentry/r-novice-inflammation/master/tic.R (not your typical R file but the error should not occur)

```
TypeError: Cannot read property 'split' of undefined
    at Parser_1.default.parse.environ.softwareRequirements.Promise.all.packages.map (/snapshot/dockter/dist/RParser.js:122:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
undefined
```

**Comment by nokome** [comment]
Thanks for the :bug: report! This should be fixed in 0.2.2 available on the releases page. Please close this if that works.

**Comment by apawlik** [comment]
I got the bug using 0.2.2

**Comment by apawlik** [comment]
OK, downloaded fresh binary and fresh `R` examples. Now I am getting a new error. I will close this issue and open a new one
