### ISSUE TITLE
install-latest-linux.sh fails

### ISSUE THREAD

**Issue by remram44** [stencila/dockter#56]
`install-latest-linux.sh` does not create `.local/bin` if it doesn't exist.

Furthermore, it downloads a tarball in the current directory (which might be a terrible location for it, or might not be writable), and leaves it behind.

**Comment by nokome** [comment]
Thanks @remram44! What do you think about these potential solutions?

- Download to `/tmp`
- Do `mkdir -p ~/.local/bin/` before `mv` from `/tmp` to `~/.local/bin/`

**Comment by remram44** [comment]
Sounds good! You can probably `rm` the tarball after too

**Comment by nokome** [comment]
Thanks. Done.
